server:
  port: 8081


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: soda
    password: root
    url: jdbc:mysql://192.168.3.100:3306/spring?serverTimezone=Asia/Shanghai

mybatis:
  mapper-locations: classpath:mapper/*.xml
